all:
  children:
    linux:
      children:
        ubuntu:
          hosts:
            herbert:
              projects:
                - name: hmtoinflux
                  url: https://github.com/debauer/HomematicToInflux
                  # branch: release-branch # master is default
                  # update: no # yes is default
                - name: tasmotatoinflux
                  url: https://github.com/debauer/tasmotaToInflux
              influx_databases:
                - tasmotaToInflux
                - homematicToInflux
                - unifi
                - telegraf
              grafana_datasources:
                - { db: tasmotaToInflux, name: tasmota}
                - { db: homematicToInflux, name: homematic, default: true }
                - { db: unifi }
                - { db: telegraf }
              grafana_admin_user: admin
              backup_script: backup_herbert.sh
            nadine:
              ansible_user: keya
            git:
              ansible_user: root
              ansible_host: git.debauer.net
              users:
                - { name: gogs }
            mail:
              ansible_user: root
              ansible_host: mail.debauer.net
              backup_script: backup_mail.sh
            storagebox:
              ansible_user: u220998
              ansible_host: u220998.your-storagebox.de
              ansible_port: 23
              key_files:
                - public_keys/bauer-bauer
                - public_keys/bauer-zerbrechlich
                - public_keys/root-git
                - public_keys/root-herbert
                - public_keys/root-mail

        arch:
          hosts:
            david:
              ansible_user: debauer
            synyx:
              ansible_user: bauer

    raspberrys:
      hosts:
        print-server:
          ansible_host: 192.168.1.107
        octopi:
          ansible_host: 192.168.1.123
        gardenpi:
          ansible_host: 192.168.1.124
        volumio:
          ansible_host: 192.168.1.125

    network:
      hosts:
        mikrotik:
          ansible_host: 192.168.1.188
          ansible_ssh_user: admin+cet512w
          ansible_ssh_pass: supergeheimespasswort
          ansible_network_os: routeros
          ansible_connection: network_cli
          dhcp:
            - iot: # we set dhcp-iot
                vlanid: 100
                lease_time: "00:01:00"
                # pool: "pool-iot" # we set after the dhcp name pool-iot
                range: "192.168.20.100-192.168.20.254"
                network:
                  address: 192.168.20.0/24
                  dns: "192.168.1.1,192.168.20.1,8.8.8.8,8.8.4.4"
                  gateway: 192.168.20.1
            - ew: # we set dhcp-david
                vlanid: 200
                lease_time: "00:01:00"
                # pool: "pool-iot" # we set after the dhcp name pool-iot
                range: "192.168.21.100-192.168.21.254"
                network:
                  address: 192.168.21.0/24
                  dns: "192.168.1.1,192.168.21.1,8.8.8.8,8.8.4.4"
                  gateway: 192.168.21.1

    china_cams:
      hosts:
        192.168.1.108
        192.168.1.126
      vars:
        telnet_user: root
        telnet_pw: xmhdipc
    tasmota:
      children:
        steckdosen:
          hosts:
            steckdose01:
              friendly_name: Drucker
              ip: 192.168.1.170
              module: 45 #blitzwolf SHP / gosund SP111
              mac: 4C:11:AE:04:2B:D3
            steckdose02:
              friendly_name: Kuehlschrank
              ip: 192.168.1.171
              module: 45 #blitzwolf SHP / gosund SP111
              mac: BC:DD:C2:30:2F:B1
            steckdose03:
              friendly_name: Geschirrspueler
              ip: 192.168.1.172
              module: 45 #blitzwolf SHP / gosund SP111
            steckdose04:
              friendly_name: Hundebrunnen
              ip: 192.168.1.173
              module: 45 #blitzwolf SHP / gosund SP111
              mac: CC:50:E3:37:62:0A
              timer: ['{"Arm":1,"Mode":0,"Time":"08:00","Window":0,"Days":"1111111","Repeat":1,"Output":1,"Action":1}',
                      '{"Arm":1,"Mode":0,"Time":"00:00","Window":0,"Days":"1111111","Repeat":1,"Output":1,"Action":0}',
                      0,0,0,0,0,0,0,0,0,0,0,0,0,0]
            steckdose05:
              friendly_name: "Nachttisch Nadine"
              ip: 192.168.1.174
              module: 55 #gosund SP1
              mac: 24:62:AB:30:A5:24
            steckdose06:
              friendly_name: Fernseher
              ip: 192.168.1.175
              module: 55 #gosund SP1
              mac: D8:F1:5B:AB:44:BC
            steckdose07:
              friendly_name: "Kueche Media"
              ip: 192.168.1.176
              module: 55 #gosund SP1
              mac: DC:4F:22:B6:B6:A5
            steckdose08:
              friendly_name: "Nachtisch David"
              ip: 192.168.1.177
              module: 55 #gosund SP1
              mac: D8:F1:5B:C0:48:29
            steckdose09:
              friendly_name: Terrarium
              ip: 192.168.1.178
              module: 52 #teckin
              mac: C4:4F:33:80:AA:B8
              timer: ['{"Arm":1,"Mode":0,"Time":"08:00","Window":0,"Days":"1111111","Repeat":1,"Output":1,"Action":1}',
                      '{"Arm":1,"Mode":0,"Time":"20:00","Window":0,"Days":"1111111","Repeat":1,"Output":1,"Action":0}',
                      0,0,0,0,0,0,0,0,0,0,0,0,0,0]
            steckdose10:
              ip: 192.168.1.179
              module: 52 #teckin
            steckdose11:
              ip: 192.168.1.180
              module: 52 #teckin
              mac: 60:01:94:A4:CC:E3
          vars:
            full_topic: "ew/steckdosen/%prefix%/%hostname%/"
        sensoren:
          children:
            feinstaub:
              hosts:
                feinstaub01:
                  ip: 192.168.1.181
                  mac: EC:FA:BC:C5:15:FF
                  gpio: [0,101,0,70,6, 5,0,0,0,0 ,0,0,0,0,0 ,0]
                  # "GPIO0":{"0":"None"}
                  # "GPIO1":{"101":"SDS0X1 Tx"}
                  # "GPIO2":{"0":"None"}
                  # "GPIO3":{"70":"SDS0X1 Rx"}
                  # "GPIO4":{"6":"I2C SDA"}
                  # "GPIO5":{"5":"I2C SCL"}
                heizung-temperatur:
                  full_topic: "ug/temperaturen/%prefix%/heizung/"
                  ip: 192.168.1.182
                  gpio: [0,0,4,0,0, 0,0,0,0,0 ,0,0,0,0,0 ,0]
                  # GPIO2":{"4":"DS18x20"}
                strommessung01:
                  ip: 192.168.1.183
                soil01:
                  ip: 192.168.1.184
                soil02:
                  ip: 192.168.1.185
                schlafzimmer:
                  ip: 192.168.1.186
                kueche:
                  ip: 192.168.1.187
                  mac: EC:FA:BC:C5:15:31
                  gpio: [5,0,6,0,0, 0,0,0,0,0 ,0,0,0,0,0 ,0]
                  # "GPIO0":{"5":"I2C SCL"}
                  # "GPIO2":{"6":"I2C SDA"}
                bad:
                  ip: 192.168.1.188
                kammer:
                  ip: 192.168.1.189
                co201:
                  ip: 192.168.1.190
                  mac: A4:CF:12:D9:0E:2C
                  gpio: [0,60,0,61,6, 5,0,0,0,0 ,0,0,0,0,0 ,0]
                  # "GPIO1":{"60":"MHZ Tx"}
                  # "GPIO3":{"61":"MHZ Rx"}
                  # "GPIO4":{"6":"I2C SDA"}
                  # "GPIO5":{"5":"I2C SCL"
                  tele_period: 20
              vars:
                full_topic: "ew/sensoren/%prefix%/%hostname%/"

      # for tasmota
      vars:
        tele_period: 10
        mqtt_user: "test"
        mqtt_pass: "1234"
        mqtt_port: 1883
        mqtt_host: 192.168.1.101
        timers_active: 0
        timer: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        module: 0 # generic
        gateway: 192.168.1.1
        netmask: 255.255.255.0
        dns: 192.168.1.1
        wlan1_ssid: bauer_2G
        wlan2_ssid: bauer_iot

  # for all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: root
    key_files:
      - public_keys/bauer-bauer
      - public_keys/bauer-zerbrechlich
    borg_retention_policy:
      keep_hourly: 3
      keep_daily: 7
      keep_weekly: 4
      keep_monthly: 6
