---
# from GitHub, overriding the name and specifying a specific tag
roles:
  - name: iot/ansible-tasmota
    src: https://github.com/tobias-richter/ansible-tasmota
    version: master

  - src: https://github.com/debauer/ansible-ssmtp
    name: basic/ansible-ssmtp

