---
# from GitHub, overriding the name and specifying a specific tag
roles:
  - name: iot/ansible-tasmota
    src: https://github.com/tobias-richter/ansible-tasmota
    version: master

  - src: https://github.com/debauer/ansible-grafana
    name: monitoring/ansible-grafana

  - src: https://github.com/debauer/ansible-role-borgbackup
    name: backup/ansible-borg
    version: multiple-configs-and-crons

  - src: https://github.com/debauer/ansible-ssmtp
    name: basic/ansible-ssmtp

  - src: https://github.com/bodsch/ansible-influxdb
    name: monitoring/ansible-influxdb
    version: 1.1.0

  - src: https://github.com/geerlingguy/ansible-role-certbot
    name: monitoring/ansible-influxdb
