---
- name: update system
  community.general.pacman:
    update_cache: true
    upgrade: true
  when:
    - ansible_facts['os_family'] == "Archlinux"

- name: Install grafana
  package:
    name: "{{ item }}"
    state: present
  with_items: [grafana]

- name: Create influxdb datasource
  grafana_datasource:
    name: "{{ item.name | d( item.db ) }}"
    grafana_url: http://{{ inventory_hostname | d('localhost') }}:{{ grafana_http_port }}
    grafana_user: admin
    grafana_password: "{{ lookup('vars', 'vault_' + inventory_hostname + '_grafana_admin_password') }}"
    ds_type: influxdb
    ds_url: http://{{ inventory_hostname | d('localhost') }}:8086
    database: "{{ item.db }}"
    time_interval: ">10s"
    is_default: "{{ item.default | d('false') }}"
  with_items: "{{ grafana.datasources }}"
  changed_when: false

- name: enable anon access
  block:
    - ini_file:
        path: /etc/grafana/grafana.ini
        section: auth.anonymous
        option: enabled
        value: "true"
        backup: true
    - ini_file:
        path: /etc/grafana/grafana.ini
        section: auth.anonymous
        option: org_name
        value: Main Org.
        backup: true
    - ini_file:
        path: /etc/grafana/grafana.ini
        section: auth.anonymous
        option: org_role
        value: Viewer
        backup: true
