---          
all:
  vars:
    stdout_callback: full_skip
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: root
    ssh_key_files:
      - public_keys/bauer-bauer
      - public_keys/bauer-zerbrechlich
    borg_retention_policy:
      keep_hourly: 3
      keep_daily: 7
      keep_weekly: 4
      keep_monthly: 6
    lxc_start_container: false
    role_influxdb: no
    influx_default_bucket: tasmota
    influx_default_user: debauer
    influx_default_org: main
    
  children:
    tasmota:
      children:
        steckdosen:
          vars:
            full_topic: "ew/steckdosen/%prefix%/%hostname%/"
        sensoren:
          vars:
            full_topic: "ew/sensoren/%prefix%/%hostname%/"
      vars:
        tele_period: 30
        mqtt_user: "test"
        mqtt_pass: "1234"
        mqtt_port: 1883
        mqtt_host: 192.168.1.101
        timers_active: 0
        timer: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        module: 0 # generic
        gateway: 192.168.1.1
        netmask: 255.255.255.0
        dns: 192.168.1.1
        wlan1_ssid: bauer_2G
        wlan2_ssid: bauer_iot
        commands:
        - command: VoltageSet
          value: 238
        - command: PowerSet
          value: 147
      