---
all:
  vars:
    stdout_callback: full_skip
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: root
    ssh_key_files:
      - public_keys/bauer-bauer
      - public_keys/bauer-zerbrechlich
    borg_retention_policy:
      keep_hourly: 3
      keep_daily: 7
      keep_weekly: 4
      keep_monthly: 6
    lxc_container:
      host: ""
      base: archbase
      state: undefined
      autostart: "0"
      groups: default
      privileged: false
      backup_before: ""
      backup_after: ""
      backup_stopped: false
      block_create: true
    role_influxdb: false
    influx_default_bucket: tasmota
    influx_default_user: debauer
    influx_default_org: main
    project:
      user_need_sudo: false

  children:
    tasmota:
      children:
        steckdosen:
          vars:
            tasmota_mqtt_fulltopic: ew/steckdosen/%prefix%/%hostname%/
        sensoren:
          vars:
            tasmota_mqtt_fulltopic: ew/sensoren/%prefix%/%hostname%/
        strom:
          vars:
            tasmota_mqtt_fulltopic: ew/strom/%prefix%/%hostname%/
      vars:
        tele_period: 30
        tasmota_mqtt_user: "test"
        tasmota_mqtt_password: "1234"
        tasmota_mqtt_port: "1883"
        tasmota_mqtt_host: "mqtt.lan"
        tasmota_mqtt_client: ""
        tasmota_mqtt_topic: "tasmota_%06X"
        timers_active: 0
        timer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        module: 0 # generic
        gateway: 192.168.1.1
        netmask: 255.255.255.0
        dns: 192.168.1.1
        wlan1_ssid: bauer_2G
        wlan2_ssid: bauer_iot
        dhcp: yes
        set_mqtt: yes
        calibration:
          voltage: 230
          power: 61.4
          current: 265
