---
all:
  children:
    container:
      children:
        container_synyx:
          hosts:
            herman_minecraft:
              ansible_host: 192.168.111.2
              nat_ports:
                - 25565:25565:tcp
              proxy:
                - port: 80
                  target: mcmap.debauer.net
              lxc_container:
                name: minecraft
                group: gameserver
            herman_mqtt:
              ansible_host: 192.168.111.3
              nat_ports:
                - 1883:1883:tcp
                - 8883:8883:tcp
              lxc_container:
                name: mqtt
            herman_automodal:
              ansible_host: 192.168.111.4
              projects:
                - name: automodal-ccs-adapter
                  user: automodal-ccs-adapter
                  url: https://github.com/Contargo/automodal-ccs-adapter
                  update_repo: true
                  user_need_sudo: true
                  install_requirements_txt: true
                - name: automodal-tams
                  user: automodal-tams
                  branch: new-gui
                  update_repo: true
                  url: https://github.com/Contargo/automodal-tams
                  user_need_sudo: true
                  install_requirements_txt: true
              proxy:
                - port: 7000
                  target: automodal-tams.debauer.net
              lxc_container:
                name: automodal

            herman_web:
              container_name: web
              ansible_host: 192.168.111.5
              lxc_container:
                name: web
                block_create: true

            herman_paperless:
              ansible_host: 192.168.111.6
              proxy:
                - port: 8000
                  target: paperless.debauer.net
              lxc_container:
                name: paperless
                state: started
                autostart: false
                block_create: false
              paperless:
                url: paperless.debauer.net

            herman_proxy:
              ansible_host: 192.168.111.7
              nat_ports:
                - 80:80:tcp
                - 443:443:tcp
              role_proxy: true
              lxc_container:
                name: proxy
            herman_filebrowser:
              ansible_host: 192.168.111.8
              proxy:
                - port: 8080
                  target: filebrowser.debauer.net
              lxc_container:
                name: filebrowser
            herman_influxdb:
              ansible_host: 192.168.111.9
              role_influxdb: true
              influxdb:
                buckets:
                  - b_tasmota
                  - b_homematic
                  - b_camper
                user:
                  u_tasmota:
                    write: b_tasmota
                  u_homematic:
                    write: b_homematic
                  u_grafana:
                    read: all
                  u_popel:
                    write: b_camper
              proxy:
                - port: 8086
                  target: influx.debauer.net
              lxc_container:
                name: influxdb
            herman_grafana:
              ansible_host: 192.168.111.10
              proxy:
                - port: 3000
                  target: grafana.debauer.net
              lxc_container:
                name: grafana
          vars:
            ansible_ssh_common_args: -o StrictHostKeyChecking=accept-new -o ProxyCommand="ssh -W %h:%p -q synyx.debauer.net"
            ansible_user: debauer
            lxc_container:
              host: herman
              base: archbase
              backup_before: ""
              backup_after: ""
              backup_stopped: false
              privileged: true
            nat_interface: eno2
            certbot_email: admin@debauer.net
