all:
  hosts:
    mail:
      ansible_user: root
      ansible_host: mail.debauer.net
      backup_script: backup_mail.sh
  vars:
    ansible_user: root
    ssh_key_files:
      - public_keys/bauer-bauer
      - public_keys/bauer-zerbrechlich
    borg_retention_policy:
      keep_hourly: 3
      keep_daily: 7
      keep_weekly: 4
      keep_monthly: 6
  