---
all:
  children:
    blech:
      hosts:
        #zerbrechlich:
        #  ip: 192.168.99.30
        #  mac: 5C:E0:C5:48:2D:B2
        #bauer-t14s:
        #  ansible_host: 192.168.99.3
        #  ip: 192.168.99.31
        #  ansible_user: debauer
        #  mac: 3C:E1:A1:B7:D8:11
        #bauer-t14s-wifi:
        #  ip: 192.168.99.32
        #  #mac: 04:7B:CB:B7:3C:9E
        #guse:
        #  ansible_host: 192.168.99.33
        #  ip: 192.168.99.33
        #  ansible_user: david.bauer
          
        #david-handy:
        #  ip: 192.168.99.40
        #  mac: E0:CC:F8:E5:9A:5A
        #nadine-tablet:
        #  ip: 192.168.99.41
        #  mac: E0:2B:E9:D8:91:81
        #nadine-handy:
        #  ip: 192.168.99.42
        #  mac: 2E:6F:50:CE:28:7C
          
        fritzbox:
          ip: 192.168.1.1
        mainswitch:
          ip: 192.168.1.103
          mac: D8:0D:17:D6:59:B7
        camera-doggos:
          ip: 192.168.1.150
          mac: 5C:E9:31:C5:49:04
        xiaomi-stick:
          ip: 192.168.1.151
          mac: EC:FA:5C:7B:7A:3D
        camera-kueche:
          ip: 192.168.1.152
          mac: 5C:E9:31:7D:06:B1
        firetv1:
          ip: 192.168.1.154
          mac: EC:0D:E4:9A:98:F0
        firetv2:
          ip: 192.168.1.155
          mac: 24:CE:33:25:1A:F6
        dishwasher:
          ip: 192.168.1.156
          mac: C8:D7:78:AA:C7:C3
        davidswitch:
          ip: 192.168.1.158
          mac: 6C:CD:D6:A2:91:B1
        octopi:
          ip: 192.168.1.169
          mac: b8:27:eb:78:3b:f6
          fqdn:
            - 3ddrucker.lan
            - ender3.lan
            - cr6.lan
        ap1:
          ip: 192.168.1.120
          mac: F0:9F:C2:A9:A2:1F
        ap2:
          description: kueche
          ip: 192.168.1.121
          mac: 78:8A:20:29:7E:25
        ap3:
          ip: 192.168.1.122
          mac: 80:2A:A8:C6:A7:9E
        ap4:
          description: David Buero
          ip: 192.168.1.123
          mac: 18:e8:29:ec:14:6a
