---
all:
  children:
    network:
      hosts:
        mikrotik:
          ansible_host: 192.168.1.2
          ansible_ssh_user: admin+cet512w
          ansible_ssh_pass: qPutv3G6Ee9vtCT
          ansible_network_os: routeros
          ansible_connection: network_cli
          ip: 192.168.1.2
          dns:
            ttl: 1h
            domain: lan
          dhcp:
            name: dhcp_main
            lease_time: 00:02:00
            pool: dhcp_pool
            range: 192.168.1.10-192.168.1.100
            networks:
              - address: 192.168.1.0/24
                dns: 192.168.1.2
                gateway: 192.168.1.1
                domain: lan
              - address: 192.168.66.0/24
                dns: 192.168.1.2
                gateway: 192.168.1.1
                domain: lan