---
- name: "start Container {{hostvars[container].container_name}}"
  become: "{{ container_as_root }}"
  lxc_container:
    name: "{{hostvars[container].container_name}}"
    state: "{{hostvars[container].lxc_container_state}}"