---
- name: copy bash config to users home
  include_tasks: bash.yml 
  args: 
    user: "{{ loop_user }}"
  with_items: "{{ users }}"
  loop_control:
    loop_var: loop_user
  when: not "{{ loop_user }}" == "root"
