---
- hosts: herbert
  become: yes
  vars_files:
    - ../vars/secrets.yml
  vars:
    influx_admin_password: "{{ vault_influx_admin_password }}"
    grafana_admin_password: "{{ vault_grafana_admin_password }}"
    update_apt: false
    users:
      - { name: videostreamer, groups: [docker] }

  roles:
    - role: roles/basic/users
    - role: roles/basic/packages



