---
- hosts: herbert
  become: yes
  vars_files:
    - ../../vars/secrets.yml
  vars:
    borg_encryption_passphrase: "{{vault_borg_pass}}"
    
  roles:
  - role: roles/backup/rsync
  - role: roles/backup/ansible-borg
    vars:
      borg_repository: /media/ext_backup/herbert/borg
      borgmatic_config_name: usb.yaml
      borg_source_directories:
        - /media/raid1
  - role: roles/backup/ansible-borg
    vars:
      borg_repository: ssh://u220998@u220998.your-storagebox.de:23/./backups/herbert
      borgmatic_config_name: hetzner.yaml
      borg_source_directories:
        - /media/raid1
      borg_exclude_patterns:
        - /media/raid1/debauer/Videos David


