---

- name: Ensure group "somegroup" exists
  group:
    name: '{{ item }}'
    state: present
  with_items: '{{ user_default_groups + user_groups }}'

- name: Add the user with a bash shell
  user:
    name: '{{ user }}'
    shell: /bin/bash
    groups: '{{ user_default_groups + user_groups }}'
    append: yes

- name: make dir .ssh
  file:
    path: /home/{{ user }}/.ssh
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0755'

- name: Set up ssh keys
  authorized_key:
    user: '{{ user }}'
    state: present
    key: '{{ loop_file }}'
  with_file: '{{ ssh_key_files }}'
  loop_control:
    loop_var: loop_file
  when: '{{ copy_keys }}'