---
- name: setup raspberry network
  include_tasks: setup.yml 
  vars:
    network: "{{ network_var }}"
  with_items: "{{ raspberry_network }}"
  loop_control:
    loop_var: network_var
    
    
- name: disable dhcpd
  ansible.builtin.systemd:
    name: dhcpcd
    enabled: false
    state: stopped
