---
- name: update system
  community.general.pacman:
    update_cache: true
    upgrade: true
  when:
    - ansible_facts['os_family'] == "Archlinux"

- name: Install prometheus
  package:
    name: "{{ item }}"
    state: present
  with_items: [prometheus, prometheus-node-exporter]
  
- name: ensure prometheus is enabled on boot
  become: true
  service:
    name: prometheus
    enabled: true
    state: started