---
- name: Install influxdb
  package:
    name: "{{ item }}"
    state: present
  with_items: [influxdb, influx-cli]

- name: ensure influxdb is enabled on boot
  become: true
  service:
    name: influxdb
    enabled: true
    state: started

- name: get all configs
  become: yes
  shell: "influx config"
  register: influx_config
  ignore_errors: true
  check_mode: false
  changed_when: False
  
- name: Create default Org
  shell: "influx config create -n default -u http://localhost:8086 -o main-org -t '{{ vault_influx_api_token }}' -a"
  when: '"default" not in influx_config.stdout'

- name: Create buckets
  shell: "influx bucket create --name {{ item }} -o main-org --token '{{ vault_influx_api_token }}'"
  with_items: "{{ influxdb.buckets }}"