# ansible-playbook -v -i ~/ansible/raspberry /playbooks/setup-camera-motion.yml
---
- hosts: gardenpi
  gather_facts: yes
  vars:
    boot_config_options:
      # Disable Camera LED 1 is disabled, 0 is enabled
      - regexp: "^#?disable_camera_led"
        line: "disable_camera_led=0"

  roles:
    - role: users
      vars:
        users:
          - { name: root }
          - { name: keya }
          - { name: debauer }
        key_files:
          - public_keys/bauer-bauer
          - public_keys/bauer-zerbrechlich
    - role: packages
      vars:
        - update_apt: true
    - role: picam