---
- name: Install docker
  community.general.pacman:
    update_cache: true
    name:
      - docker
      - docker-compose
      - python-pip
      - python-setuptools
    state: present

- name: Install general pip dependencies
  become: true
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose
      - requests
    state: present
    executable: /usr/bin/pip3

- name: Enable docker service and ensure it is not masked
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Copy docker-compose.yml to server
  ansible.builtin.template:
    src: docker-compose.j2
    dest: /home/{{ ansible_user }}/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0
  become: true

- name: Copy docker-compose.env to server
  ansible.builtin.template:
    src: docker-compose_env.j2
    dest: /home/{{ ansible_user }}/.env
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0
  become: true

- name: Run `docker-compose up` again
  community.docker.docker_compose:
    project_src: /home/{{ ansible_user }}
    build: false
  register: output

- name: Docker-compose output
  ansible.builtin.debug:
    var: output
  tags: debug
