---
- name: APT Packages
  block:
    #- name: Remove base packages
    #  package:
    #    name: "{{ packages_remove }}"
    #    state: absent

    - name: Install common packages
      package:
        name: "{{ packages_common }}"
        state: present
      when: packages_common

    - name: Install additinal packages
      package:
        name: "{{ packages_additional }}"
        state: present
      when: packages_additional
  when:
    - ansible_facts['os_family'] == "Archlinux"

- name: PIP Packages
  block:
    - name: install general pip dependencies
      become: yes
      become_user: '{{ item }}'
      pip:
        name: "{{ pip_for_users + pip_for_user_additional }}"
        state: present
        executable: /usr/bin/pip3
      with_items: "{{ users }}"

    - name: install general pip dependencies for default python3
      become: yes
      become_user: 'root'
      pip:
        name: "{{ pip_for_root + pip_for_root_additional }}"
        state: present
        executable: /usr/bin/pip3
      with_items: "{{ users }}"
  when: pip_install