---
- hosts: david
  become: yes
  vars_files:
    - ../vars/secrets.yml
  vars:
    borg_encryption_passphrase: "{{vault_borg_pass}}"
    ansible_os_family: 'Debian' # dirty fix

  roles:
    - role: roles/backup/rsync
      #hour: "*"