---
- name: set dhcp range
  routeros_command:
    commands: "/ip pool set [find name={{ hostvars[inventory_hostname].dhcp.pool }}] range={{ hostvars[inventory_hostname].dhcp.range }}"

- name: set dns servers
  routeros_command:
    commands: "/ip dhcp-server network set [find] dns-server={{ hostvars[inventory_hostname].dhcp.network.dns }}"

- name: dns setup
  block:
    - name: remove all static dns entries
      routeros_command:
        commands: "/ip dns static remove [find]"

    - name: add static dns entries
      routeros_command:
        commands:
          - "/ip dns static add address={{ hostvars[loop_host].ip }} name={{loop_host}}"
      with_items: "{{ groups['all'] }}"
      loop_control:
        loop_var: loop_host
      when: hostvars[loop_host].ip is defined
  when: update_dns

- name: dhcp setup
  block:
    - name: remove all static dhcp leases
      routeros_command:
        commands: "/ip dhcp-server lease remove [find]"

    - name: add static dhcp lease
      routeros_command:
        commands:
          - "/ip dhcp-server lease add address={{ hostvars[loop_host].ip }} mac-address={{hostvars[loop_host].mac}} server=dhcpautomodal use-src-mac=yes"
      with_items: "{{ groups['all'] }}"
      loop_control:
        loop_var: loop_host
      when: hostvars[loop_host].ip is defined and hostvars[loop_host].mac is defined
  when: update_dhcp_leases