---
- name: create dns commands
  generate_info_page:
    hostvars: "{{ hostvars }}"
    hosts: "{{ groups['all'] }}"
  register: html
  tags: dns

- debug:
    var: html
    
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/infopage
    state: directory
    mode: '0755'
    
- name: Copy infopage to server
  ansible.builtin.template:
    src: index.j2
    dest: /home/{{ ansible_user }}/infopage/index.html
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  become: true