---
- debug:
    msg: "{{ proxy_config }}"

- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ proxy_config.target }}/cert.pem
  register: letsencrypt_cert

- name: Generate new certificate if one doesn't exist.
  become: yes
  command: "certbot certonly --noninteractive --agree-tos  --email {{ proxy_config.certbot_email }} --nginx -d {{ proxy_config.target }}"
  when: not letsencrypt_cert.stat.exists