---

- name: update system
  community.general.pacman:
    update_cache: true
    upgrade: true
  when:
   - ansible_facts['os_family'] == "Archlinux"

- name: install nginx
  package:
    name: [nginx, certbot-nginx]

- name: Enable service httpd and ensure it is not masked
  ansible.builtin.systemd:
    name: nginx
    enabled: true

- name: get container list with proxy defined
  set_fact: 
    proxy_configs: "{{proxy_configs | default([]) + [
                          { 'hostname': item, 
                            'container_name': hostvars[item].container_name,
                            'container_ip': hostvars[item].ansible_host,
                            'vars': hostvars[item].proxy }
                        ]}}"
  with_items: "{{ groups.container }}"
  when: 
    - hostvars[item].proxy is defined
    - hostvars[item].container_host == container_host


- name: "create letsencrypt certs for proxy targets of container {{ container_key }}"
  include: letsencrypt.yml container_key="{{ container_key }}"
  with_items: '{{ containers }}'
  loop_control:
    loop_var: container_key
  when: 
    - hostvars[container_key].proxy is defined
    - hostvars[container_key].container_host == container_host
      

- name: copy nginx.conf to server
  template:
    src: 'nginx.j2'
    dest: '/etc/nginx/nginx.conf'
    owner: root
    group: root
    mode: 0644
  become: yes

- name: killall nginx because of strange letsencrypt nginx zombie!
  become: yes
  command: killall nginx

- name: restart nginx.server
  service:
    name: nginx
    state: restarted