---
- hosts: herbert
  become: yes
  vars_files:
    - ../vars/secrets.yml
  vars:
    influx_admin_password: "{{ vault_influx_admin_password }}"
    grafana_admin_password: "{{ vault_grafana_admin_password }}"
    update_apt: false
    users:
      - { name: videostreamer, groups: [docker] }

  roles:
    - role: roles/basic/users
    - role: roles/basic/packages




0003068b.1IPC_XM530_85X20.Nat.dss.OnvifS.HIK_V5.00.R02
V5.00.R02.0003068b.1