---
# basic stuff
- hosts: web
  become: yes
  vars:
    users: [root, debauer]
    user_groups: [sudo, docker]
    copy_keys: yes
  roles:
    - role: roles/basic/users
    - role: roles/basic/packages
    - role: roles/basic/msmtp
      
# webserver user and stuff
- hosts: web
  become: yes
  vars:
    users: [root, aor]
    user_groups: [docker]
    copy_keys: no
  roles:
    - role: roles/basic/users
    - role: roles/common/ansible-docker
      
- hosts: web
  become: yes
  vars:
    users: [monitoring]
    docker-user: monitoring
    user_groups: [docker]
    copy_keys: no
  roles:
    - role: roles/basic/users
    - role: roles/common/docker-compose
      
      