---
- debug:
    msg: "proxy config: {{ proxy_config }}"

- name: create letsencrypt certs {{ proxy_item.target }}
  include_tasks: create_cert.yml 
  vars:  
    proxy_config: "{{ proxy_item }}"
  with_items: "{{ hostvars[container_key].proxy }}"
  loop_control:
    loop_var: proxy_item
  when:
    - proxy_item.target is defined
