---
- name: update system
  community.general.pacman:
    update_cache: true
    upgrade: true
  when:
    - ansible_facts['os_family'] == "Archlinux"
    - upgrade_system is defined
    - upgrade_system

- name: install nginx
  package:
    name: [nginx, certbot-nginx ]

- name: Enable service httpd and ensure it is not masked
  ansible.builtin.systemd:
    name: nginx
    enabled: true

- name: create letsencrypt certs for proxy targets of container {{ container_key }}
  include_tasks: create_cert.yml 
  vars: 
    proxy_config: "{{ proxy_config }}"
  with_items: "{{ nginx.proxy }}"
  loop_control:
    loop_var: proxy_config
  when:
    - proxy_config.ssl is defined
    - proxy_config.ssl

- name: copy nginx.conf to server
  template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  
- name: killall nginx because of strange letsencrypt nginx zombie!
  become: true
  command: killall nginx

- name: restart nginx.server
  service:
    name: nginx
    state: restarted
